# Generated by Django 2.1.3 on 2018-12-05 23:49

import Guestinc_Registros.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjunto_archivo', models.FileField(null=True, upload_to=Guestinc_Registros.models.get_upload_to_house)),
                ('archivo_adjunto_portada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento_nombre', models.CharField(max_length=15)),
                ('descuento_codigo', models.CharField(max_length=15)),
                ('descuento_fecha_inicio', models.DateField(blank=True, null=True)),
                ('descuento_fecha_final', models.DateField(blank=True, null=True)),
                ('descuento_dias', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_detalles_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles_usuario_foto', models.FileField(null=True, upload_to=Guestinc_Registros.models.get_upload_to_user)),
                ('id_usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_nombre', models.CharField(max_length=50)),
                ('estado_nombre_abreviatura', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_nombre', models.CharField(max_length=50)),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_estado')),
            ],
        ),
        migrations.CreateModel(
            name='Guest_pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagos_num_tarjeta', models.CharField(max_length=16)),
                ('pagos_nombre_propietario', models.CharField(max_length=300)),
                ('pagos_fecha_vencimiento', models.CharField(max_length=5)),
                ('pagos_codigo_seguridad', models.CharField(max_length=3)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_fecha_inicio', models.DateField()),
                ('reserva_fecha_final', models.DateField()),
                ('reserva_num_huespedes', models.IntegerField()),
                ('reserva_total_dias', models.IntegerField()),
                ('reserva_total_pago', models.IntegerField()),
                ('reserva_dias', models.IntegerField()),
                ('reserva_telefono', models.CharField(max_length=12, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_residencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residencia_nombre', models.CharField(max_length=200)),
                ('residencia_calle', models.CharField(max_length=150)),
                ('residencia_numero_exterior', models.CharField(max_length=15)),
                ('residencia_numero_interior', models.CharField(blank=True, max_length=15, null=True)),
                ('residencia_codigo_postal', models.CharField(max_length=5)),
                ('residencia_colonia', models.CharField(max_length=150)),
                ('residencia_costo_noche', models.IntegerField()),
                ('residencia_num_huepedes', models.IntegerField()),
                ('residencia_entre_calle', models.CharField(blank=True, max_length=150, null=True)),
                ('residencia_fecha_registro', models.DateTimeField(auto_now=True)),
                ('residencia_descripcion', models.CharField(blank=True, max_length=4000, null=True)),
                ('id_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_descuento')),
                ('id_estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_estatus')),
                ('id_municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_municipio')),
                ('id_reserva', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Guest_servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicios_num_cuartos', models.CharField(max_length=2)),
                ('servicios_num_camas', models.CharField(max_length=2)),
                ('servicios_num_banos', models.CharField(max_length=2)),
                ('servicios_tv_cable', models.BooleanField(default=False)),
                ('servicios_alberca', models.BooleanField(default=False)),
                ('servicios_internet', models.BooleanField(default=False)),
                ('servicios_jacuzzi', models.BooleanField(default=False)),
                ('servicios_otros', models.BooleanField(default=False)),
                ('servicios_otros_servicios', models.CharField(blank=True, max_length=4000, null=True)),
                ('id_recidencia', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_residencias')),
            ],
        ),
        migrations.CreateModel(
            name='Guest_telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_numero', models.CharField(max_length=13)),
                ('telefono_observaciones', models.CharField(max_length=200)),
                ('id_recidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestinc_Registros.Guest_residencias')),
            ],
        ),
        migrations.CreateModel(
            name='Guest_tipo_residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recidencia_nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_tipo_telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_telefono_nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Guest_valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion_numero', models.IntegerField()),
                ('valoracion_comentario', models.CharField(blank=True, max_length=4000, null=True)),
                ('id_usuario', models.CharField(blank=True, max_length=5, null=True)),
                ('id_residencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_residencias')),
            ],
        ),
        migrations.CreateModel(
            name='Guest_valoracion_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion_usuario', models.IntegerField()),
                ('valoracion_usuario_comentarios', models.CharField(max_length=4000)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='passwordRecovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordRecoveryUser', models.CharField(max_length=255)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guest_telefono',
            name='id_tipo_telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_tipo_telefono'),
        ),
        migrations.AddField(
            model_name='guest_residencias',
            name='id_tipo_residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_tipo_residencia'),
        ),
        migrations.AddField(
            model_name='guest_residencias',
            name='id_usuario_residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guest_adjunto',
            name='id_residencias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guestinc_Registros.Guest_residencias'),
        ),
    ]
