# Generated by Django 2.1.3 on 2018-12-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guestinc_Registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest_reserva',
            name='reserva_total_dias',
        ),
        migrations.AlterField(
            model_name='guest_tipo_residencia',
            name='tipo_recidencia_nombre',
            field=models.CharField(max_length=30),
        ),
    ]
